// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service/service.proto

package service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SetEnabledRequest struct {
	Enabled              bool     `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetEnabledRequest) Reset()         { *m = SetEnabledRequest{} }
func (m *SetEnabledRequest) String() string { return proto.CompactTextString(m) }
func (*SetEnabledRequest) ProtoMessage()    {}
func (*SetEnabledRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e51e679f9ae460e2, []int{0}
}

func (m *SetEnabledRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetEnabledRequest.Unmarshal(m, b)
}
func (m *SetEnabledRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetEnabledRequest.Marshal(b, m, deterministic)
}
func (m *SetEnabledRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetEnabledRequest.Merge(m, src)
}
func (m *SetEnabledRequest) XXX_Size() int {
	return xxx_messageInfo_SetEnabledRequest.Size(m)
}
func (m *SetEnabledRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetEnabledRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetEnabledRequest proto.InternalMessageInfo

func (m *SetEnabledRequest) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

type SetEnabledResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetEnabledResponse) Reset()         { *m = SetEnabledResponse{} }
func (m *SetEnabledResponse) String() string { return proto.CompactTextString(m) }
func (*SetEnabledResponse) ProtoMessage()    {}
func (*SetEnabledResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e51e679f9ae460e2, []int{1}
}

func (m *SetEnabledResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetEnabledResponse.Unmarshal(m, b)
}
func (m *SetEnabledResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetEnabledResponse.Marshal(b, m, deterministic)
}
func (m *SetEnabledResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetEnabledResponse.Merge(m, src)
}
func (m *SetEnabledResponse) XXX_Size() int {
	return xxx_messageInfo_SetEnabledResponse.Size(m)
}
func (m *SetEnabledResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetEnabledResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetEnabledResponse proto.InternalMessageInfo

func (m *SetEnabledResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type TimerProto struct {
	TimerTag             string   `protobuf:"bytes,1,opt,name=timerTag,proto3" json:"timerTag,omitempty"`
	BeginSec             int64    `protobuf:"varint,2,opt,name=beginSec,proto3" json:"beginSec,omitempty"`
	BeginNsec            int32    `protobuf:"varint,3,opt,name=beginNsec,proto3" json:"beginNsec,omitempty"`
	EndSec               int64    `protobuf:"varint,4,opt,name=endSec,proto3" json:"endSec,omitempty"`
	EndNsec              int32    `protobuf:"varint,5,opt,name=endNsec,proto3" json:"endNsec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimerProto) Reset()         { *m = TimerProto{} }
func (m *TimerProto) String() string { return proto.CompactTextString(m) }
func (*TimerProto) ProtoMessage()    {}
func (*TimerProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_e51e679f9ae460e2, []int{2}
}

func (m *TimerProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimerProto.Unmarshal(m, b)
}
func (m *TimerProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimerProto.Marshal(b, m, deterministic)
}
func (m *TimerProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimerProto.Merge(m, src)
}
func (m *TimerProto) XXX_Size() int {
	return xxx_messageInfo_TimerProto.Size(m)
}
func (m *TimerProto) XXX_DiscardUnknown() {
	xxx_messageInfo_TimerProto.DiscardUnknown(m)
}

var xxx_messageInfo_TimerProto proto.InternalMessageInfo

func (m *TimerProto) GetTimerTag() string {
	if m != nil {
		return m.TimerTag
	}
	return ""
}

func (m *TimerProto) GetBeginSec() int64 {
	if m != nil {
		return m.BeginSec
	}
	return 0
}

func (m *TimerProto) GetBeginNsec() int32 {
	if m != nil {
		return m.BeginNsec
	}
	return 0
}

func (m *TimerProto) GetEndSec() int64 {
	if m != nil {
		return m.EndSec
	}
	return 0
}

func (m *TimerProto) GetEndNsec() int32 {
	if m != nil {
		return m.EndNsec
	}
	return 0
}

type GetMessageStatsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMessageStatsRequest) Reset()         { *m = GetMessageStatsRequest{} }
func (m *GetMessageStatsRequest) String() string { return proto.CompactTextString(m) }
func (*GetMessageStatsRequest) ProtoMessage()    {}
func (*GetMessageStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e51e679f9ae460e2, []int{3}
}

func (m *GetMessageStatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessageStatsRequest.Unmarshal(m, b)
}
func (m *GetMessageStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessageStatsRequest.Marshal(b, m, deterministic)
}
func (m *GetMessageStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessageStatsRequest.Merge(m, src)
}
func (m *GetMessageStatsRequest) XXX_Size() int {
	return xxx_messageInfo_GetMessageStatsRequest.Size(m)
}
func (m *GetMessageStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessageStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessageStatsRequest proto.InternalMessageInfo

type StatProto struct {
	StatTag              string        `protobuf:"bytes,1,opt,name=statTag,proto3" json:"statTag,omitempty"`
	TimerProtos          []*TimerProto `protobuf:"bytes,2,rep,name=timerProtos,proto3" json:"timerProtos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *StatProto) Reset()         { *m = StatProto{} }
func (m *StatProto) String() string { return proto.CompactTextString(m) }
func (*StatProto) ProtoMessage()    {}
func (*StatProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_e51e679f9ae460e2, []int{4}
}

func (m *StatProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatProto.Unmarshal(m, b)
}
func (m *StatProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatProto.Marshal(b, m, deterministic)
}
func (m *StatProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatProto.Merge(m, src)
}
func (m *StatProto) XXX_Size() int {
	return xxx_messageInfo_StatProto.Size(m)
}
func (m *StatProto) XXX_DiscardUnknown() {
	xxx_messageInfo_StatProto.DiscardUnknown(m)
}

var xxx_messageInfo_StatProto proto.InternalMessageInfo

func (m *StatProto) GetStatTag() string {
	if m != nil {
		return m.StatTag
	}
	return ""
}

func (m *StatProto) GetTimerProtos() []*TimerProto {
	if m != nil {
		return m.TimerProtos
	}
	return nil
}

func init() {
	proto.RegisterType((*SetEnabledRequest)(nil), "SetEnabledRequest")
	proto.RegisterType((*SetEnabledResponse)(nil), "SetEnabledResponse")
	proto.RegisterType((*TimerProto)(nil), "TimerProto")
	proto.RegisterType((*GetMessageStatsRequest)(nil), "GetMessageStatsRequest")
	proto.RegisterType((*StatProto)(nil), "StatProto")
}

func init() { proto.RegisterFile("service/service.proto", fileDescriptor_e51e679f9ae460e2) }

var fileDescriptor_e51e679f9ae460e2 = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xe9, 0xe6, 0xe6, 0xfa, 0x76, 0x10, 0x23, 0xce, 0x32, 0x3c, 0x94, 0x9e, 0x7a, 0x59,
	0x3a, 0x26, 0x82, 0x67, 0x41, 0x3c, 0x29, 0xa3, 0xdb, 0xc9, 0x5b, 0xd7, 0x3d, 0x43, 0xa1, 0x36,
	0x35, 0x2f, 0xf3, 0xe4, 0x9f, 0xe1, 0x1f, 0x2c, 0x49, 0x9b, 0x76, 0xe8, 0x4e, 0xed, 0x2f, 0xf9,
	0x3e, 0xf2, 0x7d, 0x8f, 0x07, 0xd7, 0x84, 0xea, 0xab, 0xc8, 0x31, 0x69, 0xbf, 0xbc, 0x56, 0x52,
	0xcb, 0x68, 0x01, 0x97, 0x1b, 0xd4, 0x4f, 0x55, 0xb6, 0x2b, 0x71, 0x9f, 0xe2, 0xe7, 0x01, 0x49,
	0xb3, 0x00, 0xce, 0xb1, 0x39, 0x09, 0xbc, 0xd0, 0x8b, 0x27, 0xa9, 0xc3, 0x88, 0x03, 0x3b, 0x96,
	0x53, 0x2d, 0x2b, 0x42, 0xa3, 0xa7, 0x43, 0x9e, 0x23, 0x91, 0xd3, 0xb7, 0x18, 0xfd, 0x78, 0x00,
	0xdb, 0xe2, 0x03, 0xd5, 0xda, 0xbc, 0xc6, 0xe6, 0x30, 0xd1, 0x86, 0xb6, 0x99, 0xb0, 0x4a, 0x3f,
	0xed, 0xd8, 0xdc, 0xed, 0x50, 0x14, 0xd5, 0x06, 0xf3, 0x60, 0x10, 0x7a, 0xf1, 0x30, 0xed, 0x98,
	0xdd, 0x82, 0x6f, 0xff, 0x5f, 0x09, 0xf3, 0x60, 0x18, 0x7a, 0xf1, 0x28, 0xed, 0x0f, 0xd8, 0x0c,
	0xc6, 0x58, 0xed, 0x8d, 0xef, 0xcc, 0xfa, 0x5a, 0x6a, 0x6a, 0xec, 0xad, 0x67, 0x64, 0x3d, 0x0e,
	0xa3, 0x00, 0x66, 0xcf, 0xa8, 0x5f, 0x90, 0x28, 0x13, 0xb8, 0xd1, 0x99, 0xa6, 0xb6, 0x7a, 0xb4,
	0x05, 0xdf, 0x70, 0x13, 0xd7, 0xf4, 0xd2, 0x99, 0xee, 0xd3, 0x3a, 0x64, 0x0b, 0x98, 0xea, 0xae,
	0x16, 0x05, 0x83, 0x70, 0x18, 0x4f, 0x57, 0x53, 0xde, 0x57, 0x4d, 0x8f, 0xef, 0x57, 0xdf, 0xe0,
	0xaf, 0x95, 0x7c, 0x2f, 0xca, 0xa2, 0x12, 0xec, 0x1e, 0xa0, 0x9f, 0x21, 0x63, 0xfc, 0xdf, 0xfc,
	0xe7, 0x57, 0xfc, 0xc4, 0x90, 0x1f, 0xe0, 0xe2, 0x4f, 0x66, 0x76, 0xc3, 0x4f, 0xb7, 0x98, 0x03,
	0xef, 0x4a, 0x2c, 0xbd, 0xc7, 0xe5, 0x1b, 0x17, 0x52, 0x8a, 0x12, 0xb9, 0x90, 0x65, 0x56, 0x09,
	0x2e, 0x95, 0x48, 0x84, 0xaa, 0xf3, 0xa4, 0x76, 0xa1, 0x12, 0xbb, 0x0d, 0x6e, 0x37, 0x76, 0x63,
	0x8b, 0x77, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2c, 0xe3, 0x4f, 0xda, 0x35, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProfilingClient is the client API for Profiling service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProfilingClient interface {
	SetEnabled(ctx context.Context, in *SetEnabledRequest, opts ...grpc.CallOption) (*SetEnabledResponse, error)
	GetMessageStats(ctx context.Context, in *GetMessageStatsRequest, opts ...grpc.CallOption) (Profiling_GetMessageStatsClient, error)
}

type profilingClient struct {
	cc *grpc.ClientConn
}

func NewProfilingClient(cc *grpc.ClientConn) ProfilingClient {
	return &profilingClient{cc}
}

func (c *profilingClient) SetEnabled(ctx context.Context, in *SetEnabledRequest, opts ...grpc.CallOption) (*SetEnabledResponse, error) {
	out := new(SetEnabledResponse)
	err := c.cc.Invoke(ctx, "/Profiling/SetEnabled", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilingClient) GetMessageStats(ctx context.Context, in *GetMessageStatsRequest, opts ...grpc.CallOption) (Profiling_GetMessageStatsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Profiling_serviceDesc.Streams[0], "/Profiling/GetMessageStats", opts...)
	if err != nil {
		return nil, err
	}
	x := &profilingGetMessageStatsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Profiling_GetMessageStatsClient interface {
	Recv() (*StatProto, error)
	grpc.ClientStream
}

type profilingGetMessageStatsClient struct {
	grpc.ClientStream
}

func (x *profilingGetMessageStatsClient) Recv() (*StatProto, error) {
	m := new(StatProto)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ProfilingServer is the server API for Profiling service.
type ProfilingServer interface {
	SetEnabled(context.Context, *SetEnabledRequest) (*SetEnabledResponse, error)
	GetMessageStats(*GetMessageStatsRequest, Profiling_GetMessageStatsServer) error
}

// UnimplementedProfilingServer can be embedded to have forward compatible implementations.
type UnimplementedProfilingServer struct {
}

func (*UnimplementedProfilingServer) SetEnabled(ctx context.Context, req *SetEnabledRequest) (*SetEnabledResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetEnabled not implemented")
}
func (*UnimplementedProfilingServer) GetMessageStats(req *GetMessageStatsRequest, srv Profiling_GetMessageStatsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetMessageStats not implemented")
}

func RegisterProfilingServer(s *grpc.Server, srv ProfilingServer) {
	s.RegisterService(&_Profiling_serviceDesc, srv)
}

func _Profiling_SetEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetEnabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilingServer).SetEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Profiling/SetEnabled",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilingServer).SetEnabled(ctx, req.(*SetEnabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profiling_GetMessageStats_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetMessageStatsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProfilingServer).GetMessageStats(m, &profilingGetMessageStatsServer{stream})
}

type Profiling_GetMessageStatsServer interface {
	Send(*StatProto) error
	grpc.ServerStream
}

type profilingGetMessageStatsServer struct {
	grpc.ServerStream
}

func (x *profilingGetMessageStatsServer) Send(m *StatProto) error {
	return x.ServerStream.SendMsg(m)
}

var _Profiling_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Profiling",
	HandlerType: (*ProfilingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetEnabled",
			Handler:    _Profiling_SetEnabled_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetMessageStats",
			Handler:       _Profiling_GetMessageStats_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service/service.proto",
}
